ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'ORDER_CONFIRMATION';
ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'PAYMENT_CONFIRMATION';
ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'WALLET_TOP_UP';
ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'WALLET_CHANGE';
